# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  xls_spacing_rows: <%= ENV.fetch('XLS_SPACING_ROWS') { 3 } %>
  xls_spacing_columns: <%= ENV.fetch('XLS_SPACING_COLUMNS') { 2 } %>
  xls_header_bg_color: "<%= ENV.fetch('XLS_HEADER_BG_COLOR') { 'E8F4FF' } %>"
  xls_header_fg_color: "<%= ENV.fetch('XLS_HEADER_FG_COLOR') { '333333' } %>"
  xls_header_border_color: "<%= ENV.fetch('XLS_ROW_BORDER_COLOR') { '000000' } %>"
  xls_row_bg_color: "<%= ENV.fetch('XLS_ROW_BG_COLOR') { 'FAFAFA' } %>"
  xls_row_fg_color: "<%= ENV.fetch('XLS_ROW_FG_COLOR') { '000000' } %>"
  xls_row_border_color: "<%= ENV.fetch('XLS_ROW_BORDER_COLOR') { '333333' } %>"
  xls_empty_bg_color: "<%= ENV.fetch('XLS_ROW_BG_COLOR') { 'FFFFFF' } %>"
  placeholder_url: "<%= ENV.fetch('PLACEHOLDER_URL') { '//via.placeholder.com' } %>"
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_username: <%= ENV['MAILER_USERNAME'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  email_address: <%= ENV['DEFAULT_EMAIL_ADDRESS'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  host: <%= ENV['HOST'] %>
  max_requests_per_second: <%= ENV.fetch("MAX_REQUESTS_PER_SECOND", 5) %>
  registration_reward_points: <%= ENV['REGISTRATION_REWARD_POINTS'] %>
  first_ticket_reward_points: <%= ENV['FIRST_TICKET_REWARD_POINTS'] %>
  ticket_reward_points: <%= ENV['TICKET_REWARD_POINTS'] %>
  penalized_ticket_reward_points: <%= ENV['PENALIZED_TICKET_REWARD_POINTS'] %>
  client_max_body_size: <%= ENV['CLIENT_MAX_BODY_SIZE'] %>
  max_ticket_refund: <%= ENV['MAX_TICKET_REFUND'] %>
  # They could want to call it by a name like General
  initial_segment_name: <%= ENV.fetch('INITIAL_SEGMENT_NAME') { 'initial' } %>
  max_audits: <%= ENV['MAX_AUDITS'] %>
  aws_base_arn: <%= ENV['AWS_BASE_ARN'] %>
  aws_sns_arn: <%= ENV['AWS_SNS_ARN'] %>
  boost_points_limit: <%= ENV['BOOST_POINTS_LIMIT'] %>
  database_cleaner_trigger: <%= ENV['DATABASE_CLEANER_TRIGGER'] %>
  async_export_limit: <%= ENV.fetch('DATABASE_ASYNC_EXPORT_CONCURRENCY', 3) %>
  database_backup_storage_time: <%= ENV.fetch('DATABASE_BACKUP_STORAGE_TIME', 7) %>

development: &development
  <<: *common
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c
  email_recipients_interceptors: <%= ENV['EMAIL_RECIPIENTS_INTERCEPTOR'] %>
test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  <<: *common
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
