source 'https://rubygems.org'

ruby '~> 2.6.0'
gem 'bootsnap', '>= 1.1.0', '< 1.4.2'
gem 'rails', '~> 5.2.0'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 3.12'

# APM
gem 'newrelic_rpm'

# Authentication
gem 'devise', '~> 4.7.1'

# Easy time difference
gem 'time_difference'

gem 'devise_token_auth', '~> 1.1.3'
gem 'omniauth', '~> 1.9.0'

# API Serializers
gem 'fast_jsonapi', '~> 1.5'

# Sidekiq
gem 'sidekiq', '~> 5.2'
gem 'sidekiq-failures', '~> 1.0.0'
gem 'sidekiq-scheduler', '~> 3.0.0'
gem 'sidekiq_mailer', '~> 0.0.8'
# Authorization Policies
gem 'pundit', '~> 2.1.0'

# User Roles Management
gem 'rolify', '~> 5.2.0'

# Exceptions Report
gem 'rollbar', '~> 2.19.2'

gem 'recipient_interceptor', '~> 0.2.0'

# CORS support
gem 'rack-cors', '~> 1.0.2', require: 'rack/cors'

# Use for DoS attacks
gem 'rack-attack', '~> 5.4.2'

# Security health check
gem 'health_check', '~> 3.0'

# Use an API-Compatible backoffice
gem 'administrate', '~> 0.11.0'
gem 'inline_svg'
gem 'administrate-field-jsonb', '~> 0.4.2'
gem 'administrate-field-nested_has_many', '~> 1.2.0'
gem 'administrate-field-active_storage', '~> 0.1.8'

# Administrate uses kaminari to paginate
gem 'kaminari-i18n', '~> 0.5.0'

# Use slim templates with devise
gem 'slim', '~> 4.0.1'

# Show results as table
gem 'json2table'

# Add I18n to devise
gem 'devise-i18n', '~> 1.8.2'

# Add devise security
gem 'devise-security', '~> 0.14.3'
# Required by devise-security
gem 'email_address', '~> 0.1.11'

# Common rails terminology localization
gem 'rails-i18n', '~> 5.1'

# Coffee script for rails
gem 'coffee-rails', '~> 4.2.2'

gem 'active_record_doctor', group: :development

# Handle money
gem 'money-rails', '~>1.12'

# A nice slider for tickets
gem 'flex-slider-rails', '~> 2.7.0'

# Single purpose POROS
gem 'interactor-rails', '~> 2.0'

# Aws S3
gem 'aws-sdk-core'
# gem 'aws-sdk-s3'
gem 'aws-sdk-sns'

# Azure Blob Storage
gem 'azure-storage-blob', '~> 2.0'

# Image miniatures generation
gem 'mini_magick'

# Fake data generators
gem 'factory_bot_rails', '~> 5.0.1'
gem 'faker'

# Pagination
gem 'api-pagination', '~> 4.8.2'
gem 'pagy', '~> 2.1.5'

# Attributes Encryption
gem 'attr_encrypted', '~> 3.1.0'

# Soft Deletes
gem 'paranoia', '~> 2.2'

# Validate URIs
gem 'uri_format_validator', '~> 0.2.1'

# Some icons
gem 'font-awesome-rails', '~> 4.7.0.5'

gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
gem 'axlsx_rails', '~> 0.5.2'

gem 'timeliness-i18n', '~> 0.6.0'
gem 'validates_timeliness', '~> 5.0.0.alpha3'

# Manage views in Rails
gem 'scenic', '~> 1.5.1'

# I18n from JS
gem 'i18n-js', '~> 3.3.0'

# Add audit to all actions for future metrics
gem 'audited', '~> 4.7'

# Clean wrong UTF-8 characters
gem 'utf8-cleaner'

# Imports
gem 'activerecord-import', '~> 1.0.1'

# JQuery plugins
gem 'jquery-ui-rails', '~> 6.0.1'

# Required by newer devise versions
gem 'email_validator', '~> 2.0.1'

# # Monitoring tool
# gem 'elastic-apm', '~> 3.1.0'
gem 'parallel_tests', group: [:development, :test]

# Required by deploy
group :assets do

  gem 'sass-rails', '~> 5.0.7'
  gem 'uglifier', '~> 4.1.20'
end

group :development do
  # Generate ERD
  gem 'listen', '~> 3.1.5'
  gem 'rails-erd'
  # Gem to detect N+1 queries
  gem 'bullet', '~> 5.9.0'
  # Spring speeds up development by keeping your application running in the background.
  # Read more: https://github.com/rails/spring
  gem 'spring', '~> 2.0.2'
  gem 'spring-watcher-listen', '~> 2.0.1'
end

group :development, :test do
  gem 'awesome_print', '~> 1.8.0'

  # Loads ENV variables from .env file in base folder
  gem 'dotenv-rails', '~> 2.7.1'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 11.0.0', platform: :mri

  # Lints
  gem 'rubocop', require: false
  gem 'rubocop-faker'
  gem 'rubocop-rspec', '~> 1.32'

  # Static analysis for security vulnerabilities
  gem 'brakeman', '~> 4.5.1', require: false
end

group :test do
  # Cleans Test Database bedore running
  gem 'database_cleaner', '~> 1.7.0'

  # Test Suite
  gem 'rspec-mocks', '~> 3.8.0'
  gem 'rspec-rails', '~> 3.8.2'

  # Test formats
  gem 'rspec_junit_formatter', '~> 0.4.1'

  # Default Matchers Extension
  gem 'shoulda-matchers', '~> 4.0.1'

  # Time Mock
  gem 'timecop', '~> 0.9.1'

  # External Services Mock
  gem 'webmock', '~> 3.5.1'

  # CodeStats
  gem 'rubycritic', '~> 4.0.0', require: false
  gem 'simplecov', '~> 0.16.1', require: false
  gem 'simplecov-cobertura', '~> 1.3', '>= 1.3.1'

  # Solves 'NoMethodError: assert_template has been extracted to a gem.' as suggested by rspec
  # This error was thrown when using `expect(response).to render_template('template')`
  gem 'rails-controller-testing', '~> 1.0.4'

  gem 'rack-test', '~> 1.1.0', require: 'rack/test'
end

group :production do
  gem 'rails_12factor', '~> 0.0.3'
end
